sudo : required

services:
          - docker

before_install:
          - docker build -t new-test-image -f Dockerfile.dev .

script:
          - docker run -e CI=true new-test-image npm run test

deploy:
      provider: elasticbeanstalk
      region: "us-east-2"

      app: "docker-react"
      env: "Dockerreact-env"

      bucket_name: "elasticbeanstalk-us-east-2-411084716658"
      bucket_path: "docker-react"

      on:
          branch: "master" 
      
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key:
                    secure: $AWS_SECRET_KEY