sudo : required

services:
          - docker

before_install:
          - docker build -t sukumarpradhan/docker-react -f Dockerfile.dev .

script:
          - docker run -p 80 -e CI=true sukumarpradhan/docker-react npm run test

deploy:
      provider: elasticbeanstalk
      region: "us-east-2"

      app: "docker-react"
      env: "Dockerreact-env"

      bucket_name: "elasticbeanstalk-us-east-2-411084716658"
      bucket_path: "docker-react"

      on:
          branch: "master" 
      
      access_key_id: "$AWSACCESSKEY"
      secret_access_key: "$AWSSECRETKEY"