# This file is renamed to stop getting detected by AWS-ELB Prod deployment, Its made for local multi-container dev purposes. 

version: "3"
        
services:
                   
        react-app:
                                
                build:
                                        
                        context: .
                                        
                        dockerfile: Dockerfile.dev
                                        
                ports:
                                
                        - "3000:3000"
                                        
                volumes:
                                
                        - .:/usr/app
            
        tests:
                build:
                                
                        context: .

                        dockerfile: Dockerfile.dev
                                
                volumes:
                                
                        - .:/usr/app
                        
                command : ["npm", "run", "test"]                        
